---
name: monster-ui-application-accounts
base_branch: 'origin/5.0'
exposure: private
metapackage:
  - name: meta-monster-ui
    branch: '5.0'
    package: monster-ui-application-accounts
    type: required
base_core: monster-ui
template: monster-ui-application.spec.tmpl
package:
  centos7:
    name: monster-ui-application-accounts
    app_name: accounts
    license: "MPL 2.0"
    group: Productivity/Telephony
    url: http://www.2600hz.org/
    vendor: 2600Hz
